### ISSUE TITLE
 node-gyp failed to rebuild '/node_modules/@jsxc/jsxc/node_modules/node-sass'

### ISSUE THREAD

**Issue by raphael10-collab** [jsxc/jsxc#1037]
I tried to install jsx in my Electron-React-Typescript-Webpack app but it failed:

    yarn add @jsxc/jsxc
    
    An unhandled error occurred inside electron-rebuild
    node-gyp failed to rebuild '/home/raphy/Raphy-Template/node_modules/@jsxc/jsxc/node_modules/node-sass'.
    Error: `make` failed with exit code: 2
    
    
    
    Error: node-gyp failed to rebuild '/home/raphy/Raphy-Template/node_modules/@jsxc/jsxc/node_modules/node-sass'.
    Error: `make` failed with exit code: 2
    
    
        at ModuleRebuilder.rebuildNodeGypModule (/home/raphy/Raphy-Template/node_modules/electron-rebuild/lib/src/module-rebuilder.js:193:19)
        at processTicksAndRejections (internal/process/task_queues.js:95:5)
        at async Rebuilder.rebuildModuleAt (/home/raphy/Raphy-Template/node_modules/electron-rebuild/lib/src/rebuild.js:190:9)
        at async Rebuilder.rebuild (/home/raphy/Raphy-Template/node_modules/electron-rebuild/lib/src/rebuild.js:152:17)
        at async /home/raphy/Raphy-Template/node_modules/electron-rebuild/lib/src/cli.js:146:9

"electron-rebuild": "^2.3.5"
"electron-rebuild": "^2.3.5"
node: v14.17.0
O.S.: Ubuntu 20.04 Desktop

**Comment by sualko** [comment]
Since node-sass is deprecated we replaced it with dart-sass in the current master. Either you wait a few days for the next release, or you install it from Github. Sorry, that I can't offer any other solution.
