### ISSUE TITLE
Following NextCloud Auth Instructions to no Avail (with LDAP on NextCloud)

### ISSUE THREAD

**Issue by stevensedory** [jsxc/jsxc#703]
### Expected behavior
Our AD users should be able to log in and use chat.
### Actual behavior
Can't log in, unless we click "log in without chat"
### Steps to reproduce the behavior
1. Follow instructions here to the T, except for "Install on NextCloud Host" part: https://github.com/jsxc/xmpp-cloud-auth/wiki
2. Try logging in
3. Notice logs say that script exitted abruptly

### Environment
- **JSXC version:** 
- **Host system and version:** NextCloud 12.0.3 on CentOS 7
- **Browser vendor and version:** Firefox, Chrome, newest
- **Any browser plugins enabled?** Tried with and without
- **XMPP server vendor and version:** Tried newest Prosody and eJabbered
- **Is your XMPP server working with other clients as expected?**  Yes, when I do internal auth.

### Logs
ejabberd.log snapshot:
2018-05-21 18:19:44.822 [critical] <0.12724.0>@extauth:loop:142 extauth script has exitted abruptly with reason 'normal'
2018-05-21 18:19:44.830 [critical] <0.12725.0>@extauth:loop:142 extauth script has exitted abruptly with reason 'normal'
2018-05-21 18:19:44.832 [critical] <0.12726.0>@extauth:loop:142 extauth script has exitted abruptly with reason 'normal'
2018-05-21 18:19:44.836 [critical] <0.12727.0>@extauth:loop:142 extauth script has exitted abruptly with reason 'normal'
2018-05-21 18:19:44.964 [info] <0.567.0>@ejabberd_listener:accept:333 (#Port<0.19009>) Accepted connection 108.23.78.99:33402 -> 23.187.0.23:5280
2018-05-21 18:19:44.964 [info] <0.12728.0>@ejabberd_http:init:163 started: {gen_tcp,#Port<0.19009>}
2018-05-21 18:19:45.180 [critical] <0.12731.0>@extauth:loop:142 extauth script has exitted abruptly with reason 'normal'
2018-05-21 18:19:45.791 [info] <0.12304.0>@ejabberd_http_bind:handle_info:508 Session timeout. Closing the HTTP bind session: <<"6b464aad48b8655cc61e0de9ffb78d4443182019">>

error.log snapshot:
2018-05-21 18:33:29.559 [critical] <0.17411.1>@extauth:loop:142 extauth script has exitted abruptly with reason 'normal'
2018-05-21 18:33:29.561 [critical] <0.17412.1>@extauth:loop:142 extauth script has exitted abruptly with reason 'normal'
2018-05-21 18:33:29.567 [critical] <0.17413.1>@extauth:loop:142 extauth script has exitted abruptly with reason 'normal'
2018-05-21 18:33:29.930 [critical] <0.17414.1>@extauth:loop:142 extauth script has exitted abruptly with reason 'normal'
2018-05-21 18:33:29.932 [critical] <0.17415.1>@extauth:loop:142 extauth script has exitted abruptly with reason 'normal'

#### Javascript
CONNECTING: null

#### JSXC
> <body rid=​"2515311614" xmlns=​"http:​/​/​jabber.org/​protocol/​httpbind" to=​"verticalcomputers.com" xml:lang=​"en" wait=​"60" hold=​"1" content=​"text/​xml;​ charset=utf-8" ver=​"1.6" xmpp:version=​"1.0" xmlns:xmpp=​"urn:​xmpp:​xbosh">​</body>​
jsxc.js:1258 < <body xmlns=​"http:​/​/​jabber.org/​protocol/​httpbind" xmlns:xmpp=​"urn:​xmpp:​xbosh" xmlns:stream=​"http:​/​/​etherx.jabber.org/​streams" sid=​"2a928bfc9955179146b89598a90d5b43568ca681" wait=​"60" requests=​"2" inactivity=​"30" maxpause=​"120" polling=​"2" ver=​"1.8" from=​"verticalcomputers.com" secure=​"true" authid=​"5625905869384740517" xmpp:version=​"1.0">​<stream:features xmlns:stream=​"http:​/​/​etherx.jabber.org/​streams">​…​</stream:features>​</body>​
jsxc.js:1261 > <body rid=​"2515311615" xmlns=​"http:​/​/​jabber.org/​protocol/​httpbind" sid=​"2a928bfc9955179146b89598a90d5b43568ca681">​…​</body>​

**Comment by MarcelWaldvogel** [comment]
> extauth script has exitted abruptly

This means `xcauth` does not want to start up. See `/var/log/xcauth/*` (or try to run it manually and check the error message)

**Comment by stevensedory** [comment]
So for whatever reason, there are no logs in the /var/log/xcauth/ folder. Also, I can't get xcauth to start. And this is what I get when I try to run xcauth.py

root@xmpp:/opt/xmpp-cloud-auth# ./xcauth.py
Traceback (most recent call last):
  File "./xcauth.py", line 3, in <module>
    from xclib.configuration import get_args
  File "/opt/xmpp-cloud-auth/xclib/__init__.py", line 3, in <module>
    import requests
ImportError: No module named requests

**Comment by stevensedory** [comment]
So apparently I was missing some python stuff. After I ran the installs more detailed here https://github.com/jsxc/xmpp-cloud-auth/blob/master/doc/Installation.md I got a bit further.

xcauth.py still will not run though. This is what prosody log is saying now:

May 22 21:00:09 portmanager	info	Activated service 'http' on [::]:5280, [*]:5280
May 22 21:00:09 portmanager	info	Activated service 'https' on [::]:5281, [*]:5281
May 22 21:00:09 portmanager	info	Activated service 's2s' on [::]:5269, [*]:5269
May 22 21:00:09 portmanager	info	Activated service 'c2s' on [::]:5222, [*]:5222
May 22 21:00:09 portmanager	info	Activated service 'legacy_ssl' on no ports
May 22 21:00:09 mod_posix	info	Prosody is about to detach from the console, disabling further console output
May 22 21:00:09 mod_posix	info	Successfully daemonized to PID 4869
May 22 21:00:09 localhost:auth_external	info	External auth with pty command /opt/xmpp-cloud-auth/xcauth.py
May 22 21:00:58 mod_bosh	info	New BOSH session, assigned it sid '07cdcd4f-2f4b-4d6a-91b8-4ba307d30cf2'
May 22 21:00:58 verticalcomputers.com:auth_external	warn	Unable to interpret data from auth process, [56 bytes]
May 22 21:01:10 mod_bosh	info	New BOSH session, assigned it sid '586ba100-7a1d-4e9a-9c09-e37378b8cfa1'
May 22 21:01:10 verticalcomputers.com:auth_external	warn	Auth process exited unexpectedly with exit 1, restarting
May 22 21:01:10 verticalcomputers.com:auth_external	warn	Error while waiting for result from auth process: unknown error
May 22 21:01:19 mod_bosh	info	New BOSH session, assigned it sid '70bc5990-5221-4caa-8c10-5c3ac5a0019d'
May 22 21:01:20 verticalcomputers.com:auth_external	warn	Auth process exited unexpectedly with exit 1, restarting
May 22 21:01:20 verticalcomputers.com:auth_external	warn	Error while waiting for result from auth process: unknown error
May 22 21:01:25 mod_bosh	info	New BOSH session, assigned it sid '76286fff-db60-4f79-b82c-4797961cbf57'
May 22 21:01:25 verticalcomputers.com:auth_external	warn	Auth process exited unexpectedly with exit 1, restarting
May 22 21:01:25 verticalcomputers.com:auth_external	warn	Error while waiting for result from auth process: unknown error

**Comment by MarcelWaldvogel** [comment]
* What happens if you run xcauth manually now? E.g. with -I or -A
* Have you configured xcauth to accept the protocol (ejabberd/prosody) that your XMPP server speaks?

**Comment by MarcelWaldvogel** [comment]
Default should be Prosody, yes. But as you mentioned you had tried both Prosody and ejabberd, I just wanted to be sure (`Error while waiting for result from auth process: unknown error` sounded like that).

`noauth` is usually returned for wrong passwords. Are your account names including `@`? Does it work with `-I` (which just checks for the existence).

Sorry that I don't have a quick solution.

**Comment by stevensedory** [comment]
No, I really appreciate your input. Let me try a few of those things and get back to you.

**Comment by stevensedory** [comment]
This is what I get with -I, putting in a domain user and the domain:

2018-05-23 07:11:41,094 DEBUG: Start external auth script 1.0.0 for prosody with endpoint: https://cloud.verticalcomputers.com/index.php/apps/ojsxc/ajax/externalApi.php
2018-05-23 07:11:41,102 DEBUG: Starting new HTTPS connection (1): cloud.verticalcomputers.com
2018-05-23 07:11:41,230 DEBUG: https://cloud.verticalcomputers.com:443 "POST /index.php/apps/ojsxc/ajax/externalApi.php HTTP/1.1" 200 44
False

**Comment by stevensedory** [comment]
So, I had previously made a local user, admin, and just noticed when I test him, it works:

2018-05-23 07:41:04,789 DEBUG: Start external auth script 1.0.0 for prosody with endpoint: https://cloud.verticalcomputers.com/index.php/apps/ojsxc/ajax/externalApi.php
2018-05-23 07:41:04,796 DEBUG: Starting new HTTPS connection (1): cloud.verticalcomputers.com
2018-05-23 07:41:04,919 DEBUG: https://cloud.verticalcomputers.com:443 "POST /index.php/apps/ojsxc/ajax/externalApi.php HTTP/1.1" 200 43
2018-05-23 07:41:04,924 INFO: Cloud says user admin@verticalcomputers.com exists
True

BUT, none of the users that can login to NC from our AD domain (as we have NC LDAP setup), show as True. All false.

**Comment by stevensedory** [comment]
Also, I tried the socket method, but this is what I get when I go to test it:

root@xmpp:/opt/xmpp-cloud-auth# telnet localhost 23664
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
Traceback (most recent call last):
  File "/opt/xmpp-cloud-auth/xcauth.py", line 13, in <module>
    args = get_args(DEFAULT_LOG_DIR, DESC, EPILOG, 'xcauth')
  File "/opt/xmpp-cloud-auth/xclib/configuration.py", line 108, in get_args
    args = parser.parse_args(args=args, config_file_contents=config_file_contents)
  File "/usr/lib/python2.7/dist-packages/configargparse.py", line 402, in parse_args
    env_vars = env_vars)
  File "/usr/lib/python2.7/dist-packages/configargparse.py", line 496, in parse_known_args
    config_streams = self._open_config_files(args)
  File "/usr/lib/python2.7/dist-packages/configargparse.py", line 717, in _open_config_files
    for f in files]
IOError: [Errno 13] Permission denied: '/etc/xcauth.conf'
Connection closed by foreign host.

**Comment by sualko** [comment]
Guess your permission for `xcauth.conf` is wrong. Did you execute the following?

```
chown prosody:prosody /etc/xcauth.conf
chmod 600 /etc/xcauth.conf
```

**Comment by sualko** [comment]
But the error message is distinct: `IOError: [Errno 13] Permission denied: '/etc/xcauth.conf'`. Maybe you use a different user?

**Comment by stevensedory** [comment]
Ah, makes sense...

But here's what it's set to:
-rw------- 1 prosody prosody  2932 May 22 20:57 xcauth.conf

I'll try 777 and see what happens...

Nope, same problem.

**Comment by stevensedory** [comment]
Would you be willing to help out more directly? I will pay for your time.

**Comment by MarcelWaldvogel** [comment]
Do you have SELinux or similar enabled? That can deny permissions in addition to the file system.

**Comment by stevensedory** [comment]
Um, ya probably, if it's on by default. It has caused me similar headaches in the past, I just didn't see anything about it anywhere until this question you just asked, so I never considered it. Will investigate.

**Comment by MarcelWaldvogel** [comment]
If instead of telnetting to the systemd-maintained socket, you run `xcauth.py -i -t generic` and then feed it with the command?

**Comment by stevensedory** [comment]
Let me try that too...

**Comment by stevensedory** [comment]
So looks like selinux ins't installed, and the above command renders the same thing with or without `-i -t generic`

If I run it on the one user I manually created within prosody, admin, it returns True. If I run it against anyone in our AD that can login to NextCloud due to the LDAP plugin, I get False.

**Comment by stevensedory** [comment]
Here's the admin account I made within prosody:

root@xmpp:/opt/xmpp-cloud-auth# ./xcauth.py -i -t generic -I admin verticalcomputers.com
2018-06-01 06:55:15,361 DEBUG: Start external auth script 1.0.0 for generic with endpoint: https://cloud.verticalcomputers.com/index.php/apps/ojsxc/ajax/externalApi.php
2018-06-01 06:55:15,369 DEBUG: Starting new HTTPS connection (1): cloud.verticalcomputers.com
2018-06-01 06:55:15,505 DEBUG: https://cloud.verticalcomputers.com:443 "POST /index.php/apps/ojsxc/ajax/externalApi.php HTTP/1.1" 200 43
2018-06-01 06:55:15,509 INFO: Cloud says user admin@verticalcomputers.com exists
True

**Comment by stevensedory** [comment]
And here's my NextCloud login, which is my AD login:

root@xmpp:/opt/xmpp-cloud-auth# ./xcauth.py -i -t generic -I steven.sedory verticalcomputers.com
2018-06-01 06:56:04,740 DEBUG: Start external auth script 1.0.0 for generic with endpoint: https://cloud.verticalcomputers.com/index.php/apps/ojsxc/ajax/externalApi.php
2018-06-01 06:56:04,748 DEBUG: Starting new HTTPS connection (1): cloud.verticalcomputers.com
2018-06-01 06:56:04,884 DEBUG: https://cloud.verticalcomputers.com:443 "POST /index.php/apps/ojsxc/ajax/externalApi.php HTTP/1.1" 200 44
False

**Comment by MarcelWaldvogel** [comment]
@stevensedory Admin works for XMPP as well?

If you want to, you can let me know about (temporary) access credentials at marcel@jsxc.ch (PGP keyid 0xCA2657B7AA0D28BB)

@sualko Do you know about any issues related to authentication against AD? LDAP?

**Comment by skug67** [comment]
I'm not sure if this is really related to the issues the original poster is having here, but I've been able to setup Nextcloud Auth to work with prosody in terms of authenticating the prosody user against the Nextcloud database, but when I sign into Nextcloud (via SAML using Apache auth-tkt authentication) there doesn't appear to be any attempt for jsxc to actually sign in -- nothing shows up in the prosody logs.

**Comment by sualko** [comment]
> Do you know about any issues related to authentication against AD? LDAP?

We never tested this setup, because in this case your XMPP server can directly authenticate against your AD/LDAP.

**Comment by stevensedory** [comment]
> your XMPP server can directly authenticate against your AD/LDAP.

So are you saying this is what we should do, and just remove the external authentication via the auth script?

**Comment by sualko** [comment]
The idea of the external auth script was to simplify authentication in scenarios where you have no AD or similar. Therefore yes, I would directly use your existing authentication backend, but keep in mind that in this case your nc admin will have no chat account.

**Comment by stevensedory** [comment]
Okay, will give that a try. Thanks!
