### ISSUE TITLE
Unable to enable app after upgrade nextcloud to 19

### ISSUE THREAD

**Issue by Chemyakyn** [jsxc/jsxc#940]
I try to fully remove ojsxc, remove it config and tables from mysql. I try to install it again. Same result like to https://www.gitmemory.com/issue/jsxc/jsxc/916/648292528.

```
# su - -c "/usr/bin/php /var/www/html/occ app:install ojsxc" -s /bin/sh apache2
ojsxc installed
An unhandled exception has been thrown:
TypeError: XMLWriter::writeAttribute() expects parameter 2 to be string, null given in /var/www/html/3rdparty/sabre/xml/lib/Writer.php:229
Stack trace:
#0 /var/www/html/3rdparty/sabre/xml/lib/Writer.php(229): XMLWriter->writeAttribute('name', NULL)
#1 /var/www/html/3rdparty/sabre/xml/lib/Writer.php(209): Sabre\Xml\Writer->writeAttribute('name', NULL)
#2 /var/www/html/3rdparty/sabre/xml/lib/Serializer/functions.php(176): Sabre\Xml\Writer->writeAttributes(Array)
#3 /var/www/html/3rdparty/sabre/xml/lib/Writer.php(101): Sabre\Xml\Serializer\standardSerializer(Object(Sabre\Xml\Writer), '')
#4 /var/www/html/3rdparty/sabre/xml/lib/Serializer/functions.php(177): Sabre\Xml\Writer->write(Array)
#5 /var/www/html/3rdparty/sabre/xml/lib/Serializer/functions.php(184): Sabre\Xml\Serializer\standardSerializer(Object(Sabre\Xml\Writer), Array)
#6 /var/www/html/3rdparty/sabre/xml/lib/Writer.php(101): Sabre\Xml\Serializer\standardSerializer(Object(Sabre\Xml\Writer), Array)
#7 /var/www/html/3rdparty/sabre/xml/lib/Serializer/functions.php(177): Sabre\Xml\Writer->write(Array)
#8 /var/www/html/3rdparty/sabre/xml/lib/Serializer/functions.php(184): Sabre\Xml\Serializer\standardSerializer(Object(Sabre\Xml\Writer), Array)
#9 /var/www/html/3rdparty/sabre/xml/lib/Writer.php(101): Sabre\Xml\Serializer\standardSerializer(Object(Sabre\Xml\Writer), Array)
#10 /var/www/html/apps/ojsxc/lib/db/iqrosterpush.php(79): Sabre\Xml\Writer->write(Array)
#11 /var/www/html/3rdparty/sabre/xml/lib/Serializer/functions.php(160): OCA\OJSXC\Db\IQRosterPush->xmlSerialize(Object(Sabre\Xml\Writer))
#12 /var/www/html/3rdparty/sabre/xml/lib/Writer.php(101): Sabre\Xml\Serializer\standardSerializer(Object(Sabre\Xml\Writer), Object(OCA\OJSXC\Db\IQRosterPush))
#13 /var/www/html/apps/ojsxc/lib/db/stanzamapper.php(48): Sabre\Xml\Writer->write(Object(OCA\OJSXC\Db\IQRosterPush))
#14 /var/www/html/apps/ojsxc/lib/rosterpush.php(106): OCA\OJSXC\Db\StanzaMapper->insert(Object(OCA\OJSXC\Db\IQRosterPush))
#15 /var/www/html/apps/ojsxc/lib/rosterpush.php(151): OCA\OJSXC\RosterPush->removeRosterItem('ttt')
#16 /var/www/html/apps/ojsxc/lib/Migration/RefreshRoster.php(69): OCA\OJSXC\RosterPush->refreshRoster()
#17 /var/www/html/lib/private/Repair.php(103): OCA\OJSXC\Migration\RefreshRoster->run(Object(OC\Repair))
#18 /var/www/html/lib/private/legacy/OC_App.php(976): OC\Repair->run()
#19 /var/www/html/lib/private/Installer.php(169): OC_App::executeRepairSteps('ojsxc', Array)
#20 /var/www/html/lib/private/legacy/OC_App.php(402): OC\Installer->installApp('ojsxc')
#21 /var/www/html/core/Command/App/Install.php(81): OC_App->enable('ojsxc')
#22 /var/www/html/3rdparty/symfony/console/Command/Command.php(255): OC\Core\Command\App\Install->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#23 /var/www/html/3rdparty/symfony/console/Application.php(1012): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#24 /var/www/html/3rdparty/symfony/console/Application.php(272): Symfony\Component\Console\Application->doRunCommand(Object(OC\Core\Command\App\Install), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#25 /var/www/html/3rdparty/symfony/console/Application.php(148): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#26 /var/www/html/lib/private/Console/Application.php(215): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#27 /var/www/html/console.php(100): OC\Console\Application->run()
#28 /var/www/html/occ(11): require_once('/var/www/html/c...')
```

**Comment by Chemyakyn** [comment]
Applied fix: https://github.com/nextcloud/jsxc.nextcloud/commit/6ae9ad2
